# Database Connection Properties
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/SerenityTherapyCenter?createDatabaseIfNotExist=true
hibernate.connection.username=root
hibernate.connection.password=mysql

# Hibernate Dialect
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Show SQL Queries in Console
hibernate.show_sql=true

# SQL queries are neatly formatted and printed.
hibernate.format_sql=true

# Hibernate Schema Management
hibernate.hbm2ddl.auto=update

# =========================== Second Level Cache =============================

hibernate.generate_statistics=true

# Enable 2nd level cache
hibernate.cache.use_second_level_cache=true

# Enable query cache
hibernate.cache.use_query_cache=true

# JCache (Ehcache 3)
hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory

# Cache provider
hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider